//! clap owns the command tree and Nestrs options; Cargo owns its argument grammar.

use std::{ffi::OsString, path::PathBuf};

use clap::{
    Arg, ArgAction, Command, Error,
    builder::{OsStringValueParser, TypedValueParser},
    error::ErrorKind,
};

/// 可直接转发给 Cargo 的子命令及本地化说明；帮助仍由 Cargo 提供。
const CARGO_COMMANDS: &[(&str, &str)] = &[
    ("check", "检查 Nestrs 声明及生成的绑定"),
    ("build", "使用 Nestrs 编译器驱动构建应用"),
    ("run", "构建并运行应用"),
    ("test", "构建并运行单元测试和集成测试"),
];

/// 只读工具链诊断的输出形式与可选缓存目录查询。
#[derive(Debug, PartialEq, Eq)]
pub(super) struct DoctorOptions {
    /// 输出带版本号的结构化信息，供外部验证脚本读取。
    pub json: bool,

    /// 显式查询此 Cargo target 下的缓存路径；不发现项目或创建目录。
    pub target_directory: Option<PathBuf>,
}

/// 图导出的工具选项与尚未改写的 Cargo 选择参数。
#[derive(Debug, PartialEq, Eq)]
pub(super) struct GraphOptions {
    /// 可选输出路径；缺省位置由具体命令根据 Cargo target 决定。
    pub output: Option<PathBuf>,

    /// 保持用户顺序和 OS 字符串身份的 Cargo 透传参数。
    pub cargo_args: Vec<OsString>,
}

/// 项目模型初始化或保存检查所需的工具选项。
#[derive(Debug, PartialEq, Eq)]
pub(super) struct InitOptions {
    /// 是否执行保存时检查；该模式输出 Cargo JSON 并只刷新项目模型。
    pub check: bool,

    /// 是否显式合并 VS Code 配置，不隐式安装或选择编辑器。
    pub vscode: bool,

    /// 可选输出路径；缺省位置由具体命令根据 Cargo target 决定。
    pub output: Option<PathBuf>,

    /// 保持用户顺序和 OS 字符串身份的 Cargo 透传参数。
    pub cargo_args: Vec<OsString>,
}

/// 完成参数分流后的命令意图，不在解析阶段启动编译。
#[derive(Debug, PartialEq, Eq)]
pub(super) enum Invocation {
    /// 只读检查固定工具链的身份和安装工件。
    Doctor(DoctorOptions),

    /// 构建并导出所选 binary 的编译期依赖图。
    Graph(GraphOptions),

    /// 为现有项目生成或刷新 rust-analyzer 模型。
    Init(InitOptions),

    /// 使用已配置的工具链执行 Cargo 子命令。
    Cargo {
        /// 已识别的 check/build/run/test 子命令名称。
        command: String,

        /// 尚未改写的 Cargo 参数，包含用户原始 -- 分隔与程序参数。
        args: Vec<OsString>,
    },

    /// 直接显示对应 Cargo 子命令的原生帮助。
    CargoHelp(String),
}

/// 声明 Cargo 的透传参数区，保留操作系统字符串和原始选项语法。
fn cargo_arguments() -> Arg {
    Arg::new("cargo_args")
        .help_heading("参数")
        .value_name("CARGO OPTIONS")
        .num_args(0..)
        .allow_hyphen_values(true)
        .value_parser(OsStringValueParser::new())
        .help("将选项原样传递给 Cargo")
}

/// 声明非空输出路径选项，允许路径本身以短横线开头。
fn output_argument(help: &'static str) -> Arg {
    Arg::new("output")
        .help_heading("选项")
        .long("output")
        .value_name("PATH")
        .allow_hyphen_values(true)
        .value_parser(OsStringValueParser::new().try_map(|value| {
            if value.is_empty() {
                Err("output path must not be empty")
            } else {
                Ok(PathBuf::from(value))
            }
        }))
        .help(help)
}

/// 声明显式写入 VS Code 设置的开关。
fn vscode_argument() -> Arg {
    Arg::new("vscode")
        .help_heading("选项")
        .long("vscode")
        .action(ArgAction::SetTrue)
        .help("将生成的配置合并到 .vscode/settings.json，保留已有设置和注释")
}

/// 建立统一帮助格式的命令节点，避免 clap 自动帮助路由覆盖现有语义。
fn command_node(name: &'static str) -> Command {
    Command::new(name)
        .disable_help_flag(true)
        .disable_help_subcommand(true)
        .subcommand_help_heading("命令")
        .help_template("{about-with-newline}\n用法：{usage}\n\n{all-args}{after-help}")
        .arg(
            Arg::new("help")
                .short('h')
                .long("help")
                .action(ArgAction::HelpLong)
                .help_heading("选项")
                .help("显示当前命令的帮助"),
        )
}

/// 把显式 help 路由加入命令树，使用本地化说明。
fn help_command() -> Command {
    // The existing route normalizer handles these help paths; this declaration
    // supplies the localized description instead of clap's autogenerated text.
    command_node("help").about("显示当前命令或指定子命令的帮助")
}

/// Adding a command here also adds its usage, help route and option metadata.
fn command() -> Command {
    command_node("cargo-nestrs")
        .bin_name("cargo nestrs")
        .version(env!("CARGO_PKG_VERSION"))
        .disable_version_flag(true)
        .arg(
            Arg::new("version")
                .short('V')
                .long("version")
                .action(ArgAction::Version)
                .help_heading("选项")
                .help("显示版本信息"),
        )
        .subcommand_required(true)
        .color(clap::ColorChoice::Never)
        .about("Nestrs 编译工具链")
        .subcommands(CARGO_COMMANDS.iter().map(|&(name, about)| {
            command_node(name).about(about).arg(cargo_arguments())
        }))
        .subcommand(
            command_node("graph")
                .about("将项目依赖图导出为可离线查看的 HTML")
                .long_about("未指定 --bin 时，导出所选 package 中所有可执行入口的依赖图；\n使用 --workspace 可选择整个工作区。每个入口独立构建并校验。\n所需 feature 未启用的入口会标记为跳过；错误会保留在报告中，并返回非零退出码。\n\n指定 --bin 时，仅导出该入口通过校验的依赖图；失败时保留原有输出文件。\n两种模式均不会执行业务 main 或服务构造函数。")
                .args_override_self(true)
                .arg(output_argument("HTML 输出路径；默认：<Cargo target 目录>/nestrs-di.html"))
                .arg(cargo_arguments())
                .after_help("可使用 Cargo 选择参数：-p/--package PACKAGE、--workspace、--bin NAME。\n使用 -p PACKAGE --features FEATURES 指定某个 package 的 feature；\n不支持同时使用 --workspace 和 --features。--all-features 对每个 package 分别生效。\n\n等价的帮助写法：cargo nestrs help graph / cargo nestrs graph help"),
        )
        .subcommand(
            command_node("init")
                .about("为现有项目初始化 Nestrs 开发环境")
                .long_about("检查所选构建目标，生成 rust-analyzer 项目数据和客户端配置。\n使用与 cargo nestrs check 相同的编译器、feature、cfg 和私有声明桥接库。\n不会修改应用的 Cargo.toml 和源码，也不会创建新项目。\n更改 feature 或工具后，可重新运行 init 刷新开发环境。")
                .args_override_self(true)
                .arg(output_argument("项目模型输出路径；默认：<Cargo target>/nestrs/ide/rust-project.json"))
                .arg(vscode_argument())
                .arg(cargo_arguments())
                .subcommand(
                    command_node("check")
                        .about("输出 Cargo JSON 诊断，并在检查成功后刷新项目模型")
                        .long_about("生成的保存时检查配置会自动调用此入口。\n输出 Cargo JSON 诊断，并在检查成功后刷新 rust-analyzer 项目模型。\n检查失败时保留上一次成功生成的模型。")
                        .args_override_self(true)
                        .arg(output_argument("项目模型输出路径；默认：<Cargo target>/nestrs/ide/rust-project.json"))
                        // Keep this reserved Nestrs option recognizable instead of
                        // accidentally forwarding it as an unknown Cargo option.
                        .arg(vscode_argument().hide(true))
                        .arg(cargo_arguments())
                        .after_help("默认检查工作区中的所有构建目标，并转发 Cargo 的目标选择、feature 和 profile 选项。\n可通过 cargo check --help 查看完整的 Cargo 选项说明。\n此命令不会修改编辑器设置，也不接受 --vscode。\n首次配置请使用 cargo nestrs init 或 cargo nestrs init --vscode。\n\n等价的帮助写法：cargo nestrs help init check / cargo nestrs init check help"),
                )
                .subcommand(help_command())
                .after_help("默认包含工作区中的所有构建目标，并转发 Cargo 的目标选择和 feature 选项。\n客户端配置写入同目录下的 rust-analyzer-settings.json，请在 LSP 客户端中加载。\nrust-analyzer 继续使用原始源码，包括尚未保存的编辑。\n\n使用 cargo nestrs init check help 查看保存时检查的选项。"),
        )
        .subcommand(
            command_node("doctor")
                .about("检查固定版本的编译器、rustc-dev 和驱动是否安装正确")
                .long_about("检查固定版本的编译器标识、rustc-dev 库、编译器驱动和私有声明桥接库。\n检查成功后输出相关路径和驱动指纹；--json 输出版本化的结构化信息。\n此命令无需项目，不构建、不安装组件，也不创建目录。")
                .arg(
                    Arg::new("json")
                        .long("json")
                        .help_heading("选项")
                        .action(ArgAction::SetTrue)
                        .help("将已验证的工具链信息输出为 JSON"),
                )
                .arg(
                    Arg::new("target-dir")
                        .long("target-dir")
                        .help_heading("选项")
                        .value_name("PATH")
                        .requires("json")
                        .value_parser(OsStringValueParser::new().try_map(|value| {
                            if value.is_empty() {
                                Err("target directory must not be empty")
                            } else {
                                Ok(PathBuf::from(value))
                            }
                        }))
                        .help("同时查询此目录对应的缓存路径；相对路径基于当前目录，需 --json"),
                )
                .after_help("NESTRS_RUSTC：指定编译器，其完整标识必须与固定工具链一致。\nNESTRS_DRIVER：指定驱动路径；默认使用 CLI 同目录下的 nestrs-driver。\nNESTRS_MACRO_BRIDGE：指定与驱动配套的私有过程宏库。\n\n等价的帮助写法：cargo nestrs help doctor / cargo nestrs doctor help"),
        )
        .subcommand(help_command())
        .after_help("使用 cargo nestrs help <COMMAND> 或 cargo nestrs <COMMAND> help 查看命令帮助。\n多级示例：cargo nestrs help init check，也可写为 init check help 或 init check --help。\ncheck/build/run/test 的帮助由 Cargo 提供，保留其完整的原始选项说明（英文）。\n\nCargo 选项会继续转发，包括 --features、--target、--manifest-path、--locked 和 --offline。\nrun/test 中 -- 后的参数会原样传递给应用或测试程序。\n构建产物：<Cargo target 目录>/nestrs/<编译器标识>/<驱动与桥接库哈希>。\n目前已关闭 rustc 增量编译；Cargo 仍会复用未变更的构建产物。\n\nNESTRS_RUSTC：指定编译器，其完整标识必须与固定工具链一致。\nNESTRS_DRIVER：指定驱动路径；默认使用 CLI 同目录下的 nestrs-driver。\nNESTRS_MACRO_BRIDGE：指定与驱动配套的私有过程宏库。")
}

/// 命令树定位结果与已消费参数范围，供后续参数分流使用。
struct Route<'a> {
    /// 已定位的 clap 命令节点。
    command: &'a Command,

    /// 已解析的子命令路径，不含程序名。
    path: Vec<OsString>,

    /// 原始参数中已被路由识别消费的数量。
    consumed: usize,

    /// 是否需要为当前命令显示帮助。
    help: bool,
}

/// Normalize the established `help` spellings using the actual clap tree. Stop
/// at options or a test filter, so a value named `help` remains an argument.
fn route<'a>(root: &'a Command, args: &[OsString]) -> Result<Route<'a>, Error> {
    let mut route = Route {
        command: root,
        path: Vec::new(),
        consumed: 0,
        help: args.is_empty(),
    };
    for arg in args {
        if arg == "--help" || arg == "-h" {
            route.help = true;
            route.consumed += 1;
            break;
        }
        if arg == "help" {
            route.help = true;
        } else if arg.as_encoded_bytes().starts_with(b"-") {
            break;
        } else if let Some(child) = route.command.find_subcommand(arg) {
            route.command = child;
            route.path.push(arg.clone());
        } else if route.path == ["test"] && !route.help {
            break;
        } else {
            let message = match (route.path.is_empty(), arg.to_str()) {
                (true, Some("create")) => "cargo nestrs create is not implemented yet; use cargo nestrs init to initialize an existing project. Run cargo nestrs init --help for usage".to_owned(),
                (true, Some("ide")) => "cargo nestrs ide has been renamed to cargo nestrs init; rerun init with your previous options to refresh generated editor commands".to_owned(),
                _ => format!("unrecognized subcommand {:?}", arg.to_string_lossy()),
            };
            return Err(route
                .command
                .clone()
                .error(ErrorKind::InvalidSubcommand, message));
        }
        route.consumed += 1;
    }
    Ok(route)
}

/// Cargo's required, separated value slots must not become Nestrs options.
/// This is an arity guard, not a Cargo validator: unknown options are preserved,
/// and optional values such as --timings=html do not consume the following token.
fn cargo_value_slot(arg: &std::ffi::OsStr) -> bool {
    matches!(
        arg.to_str(),
        Some(
            "--manifest-path"
                | "--target-dir"
                | "--config"
                | "--package"
                | "-p"
                | "--exclude"
                | "--bin"
                | "--example"
                | "--test"
                | "--bench"
                | "--target"
                | "--features"
                | "-F"
                | "--profile"
                | "--jobs"
                | "-j"
                | "--color"
                | "--message-format"
                | "--lockfile-path"
                | "--artifact-dir"
                | "--out-dir"
                | "-Z"
        )
    )
}

/// 按当前命令的真实 clap 定义识别 Nestrs 自有选项。
fn native_argument<'a>(command: &'a Command, token: &std::ffi::OsStr) -> Option<&'a Arg> {
    command.get_arguments().find(|arg| {
        arg.get_long().is_some_and(|long| {
            token == format!("--{long}").as_str()
                || token
                    .as_encoded_bytes()
                    .starts_with(format!("--{long}=").as_bytes())
        }) || arg
            .get_short()
            .is_some_and(|short| token == format!("-{short}").as_str())
    })
}

/// 分离工具选项和 Cargo 参数，并保护 Cargo 值槽及 -- 后的原始参数。
fn partition(command: &Command, args: &[OsString]) -> (Vec<OsString>, Vec<OsString>, bool) {
    if !command
        .get_arguments()
        .any(|arg| arg.get_id() == "cargo_args")
    {
        let help = super::before_separator(args)
            .iter()
            .any(|arg| arg == "--help" || arg == "-h");
        return (args.to_vec(), Vec::new(), help);
    }
    let mut native = Vec::new();
    let mut cargo = Vec::new();
    let mut args = args.iter().peekable();
    while let Some(token) = args.next() {
        if token == "--" {
            cargo.push(token.clone());
            cargo.extend(args.cloned());
            break;
        }
        if token == "--help" || token == "-h" {
            return (native, cargo, true);
        }
        if let Some(arg) = native_argument(command, token) {
            native.push(token.clone());
            if arg.get_action().takes_values()
                && !token.as_encoded_bytes().contains(&b'=')
                && args
                    .peek()
                    .is_some_and(|value| *value != "--" && *value != "--help" && *value != "-h")
            {
                native.push(args.next().unwrap().clone());
            }
        } else {
            cargo.push(token.clone());
            if cargo_value_slot(token) && args.peek().is_some_and(|value| *value != "--") {
                cargo.push(args.next().unwrap().clone());
            }
        }
    }
    (native, cargo, false)
}

/// 兼容 cargo 插件和直接调用形式，把标准帮助及原生选项解析为命令意图。
pub(super) fn parse(mut args: Vec<OsString>) -> Result<Invocation, Error> {
    // Cargo plugins receive an extra `nestrs` word; direct invocations do not.
    if args.first().is_some_and(|arg| arg == "nestrs") {
        args.remove(0);
    }
    let mut root = command();
    root.build();
    let route = route(&root, &args)?;
    let (native, cargo, help) = partition(route.command, &args[route.consumed..]);
    let help = help || route.help;
    if help
        && route.path.len() == 1
        && let Some(&(name, _)) = CARGO_COMMANDS
            .iter()
            .find(|(name, _)| route.path[0] == *name)
    {
        return Ok(Invocation::CargoHelp(name.to_owned()));
    }
    let mut normalized = vec![OsString::from("cargo-nestrs")];
    normalized.extend(route.path.iter().cloned());
    if help {
        normalized.push("--help".into());
    } else {
        normalized.extend(native);
    }
    // Parse only native options. Keeping Cargo's payload separate avoids an
    // artificial `--` being mistaken for a missing native path value, and keeps
    // the user's original separator and OS strings completely intact.
    let matches = root.clone().try_get_matches_from(normalized)?;
    let (name, matches) = matches
        .subcommand()
        .expect("the root has no action without a subcommand");
    let check = name == "init" && matches.subcommand_name() == Some("check");
    let matches = if check {
        matches.subcommand_matches("check").unwrap()
    } else {
        matches
    };
    let cargo_args = cargo;
    match name {
        "doctor" => Ok(Invocation::Doctor(DoctorOptions {
            json: matches.get_flag("json"),
            target_directory: matches.get_one::<PathBuf>("target-dir").cloned(),
        })),
        "graph" => Ok(Invocation::Graph(GraphOptions {
            output: matches.get_one::<PathBuf>("output").cloned(),
            cargo_args,
        })),
        "init" => {
            if check && matches.get_flag("vscode") {
                return Err(route.command.clone().error(ErrorKind::ArgumentConflict,
                    "init check does not modify editor settings; use cargo nestrs init --vscode for setup"));
            }
            Ok(Invocation::Init(InitOptions {
                check,
                vscode: matches.get_flag("vscode"),
                output: matches.get_one::<PathBuf>("output").cloned(),
                cargo_args,
            }))
        }
        _ => Ok(Invocation::Cargo {
            command: name.to_owned(),
            args: cargo_args,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn arguments(values: &[&str]) -> Vec<OsString> {
        values.iter().map(OsString::from).collect()
    }

    #[test]
    fn command_schema_is_consistent() {
        command().debug_assert();
    }

    #[test]
    fn doctor_preserves_text_default_and_accepts_structured_target_queries() {
        for prefix in [vec![], vec!["nestrs"]] {
            let mut args = prefix.clone();
            args.push("doctor");
            assert_eq!(
                parse(arguments(&args)).unwrap(),
                Invocation::Doctor(DoctorOptions {
                    json: false,
                    target_directory: None,
                })
            );
            args.push("--json");
            assert_eq!(
                parse(arguments(&args)).unwrap(),
                Invocation::Doctor(DoctorOptions {
                    json: true,
                    target_directory: None,
                })
            );
        }
        for args in [
            vec!["doctor", "--json", "--target-dir", "构建 with spaces"],
            vec!["doctor", "--target-dir=构建 with spaces", "--json"],
        ] {
            assert_eq!(
                parse(arguments(&args)).unwrap(),
                Invocation::Doctor(DoctorOptions {
                    json: true,
                    target_directory: Some("构建 with spaces".into()),
                })
            );
        }
    }

    #[test]
    fn doctor_rejects_missing_empty_or_non_json_target_options() {
        for args in [
            vec!["doctor", "--target-dir", "target"],
            vec!["doctor", "--json", "--target-dir"],
            vec!["doctor", "--json", "--target-dir="],
            vec!["doctor", "--json", "--target-dir", ""],
            vec!["doctor", "--json", "--target-dir", "--json"],
            vec!["doctor", "--json", "--manifest-path", "Cargo.toml"],
        ] {
            assert!(parse(arguments(&args)).is_err(), "accepted {args:?}");
        }
    }

    #[test]
    fn init_options_are_typed_without_reordering_cargo_arguments() {
        for check in [false, true] {
            let mut args = arguments(&["init"]);
            if check {
                args.push("check".into());
            }
            args.extend(arguments(&[
                "--manifest-path",
                "project with spaces/Cargo.toml",
                "--features",
                "help",
                "--output=old.json",
                "--locked",
                "--output",
                "model directory/new.json",
            ]));
            assert_eq!(
                parse(args).unwrap(),
                Invocation::Init(InitOptions {
                    check,
                    vscode: false,
                    output: Some("model directory/new.json".into()),
                    cargo_args: arguments(&[
                        "--manifest-path",
                        "project with spaces/Cargo.toml",
                        "--features",
                        "help",
                        "--locked"
                    ]),
                })
            );
        }
        assert_eq!(
            parse(arguments(&["init", "--locked", "--vscode", "--vscode"])).unwrap(),
            Invocation::Init(InitOptions {
                check: false,
                vscode: true,
                output: None,
                cargo_args: arguments(&["--locked"]),
            })
        );
    }

    #[test]
    fn cargo_value_slots_cannot_become_nestrs_options_or_help() {
        let mut cargo = arguments(&[
            "--config",
            "--output=literal",
            "--bin",
            "help",
            "--features",
            "--vscode",
            "--manifest-path",
            "--help",
            "--future-option=unchanged",
        ]);
        let mut args = arguments(&["init"]);
        args.extend(cargo.clone());
        args.extend(arguments(&["--output", "real.json", "--offline"]));
        cargo.push("--offline".into());
        assert_eq!(
            parse(args).unwrap(),
            Invocation::Init(InitOptions {
                check: false,
                vscode: false,
                output: Some("real.json".into()),
                cargo_args: cargo,
            })
        );
    }

    #[test]
    fn dash_output_is_a_path_and_root_separator_reports_a_clap_error() {
        for path in ["-", "-report.html", "--vscode"] {
            assert_eq!(
                parse(arguments(&["graph", "--output", path])).unwrap(),
                Invocation::Graph(GraphOptions {
                    output: Some(path.into()),
                    cargo_args: Vec::new()
                })
            );
        }
        assert_eq!(
            parse(arguments(&["--"])).unwrap_err().kind(),
            ErrorKind::MissingSubcommand
        );
        assert_eq!(
            parse(arguments(&["doctor", "--unknown", "--help"]))
                .unwrap_err()
                .kind(),
            ErrorKind::DisplayHelp
        );
    }
}
