[package]
name = "nestrs-query-dynamic"
version = "0.0.0"
edition = "2024"
publish = false
default-run = "nestrs-query-dynamic"

[workspace]
members = ["library"]

[dependencies]
nestrs-core = { path = "../../../../nestrs-core" }
dynamic-library = { path = "library" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[features]
extra-root = []
invalid-dynamic = []
invalid-default = []
invalid-projected = []
