[package]
name = "nestrs-macro"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["injection"]
injection = ["dep:nestrs-injection"]

[dependencies]
zyn = { workspace = true, features = ["derive", "diagnostics", "ext"] }
nestrs-injection = { path = "../nestrs-injection", optional = true }


[lib]
proc-macro = true


[dev-dependencies]
trybuild = "1"
