[package]
name = "nestrs-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
linkme = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
